name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_RIVER_0453CA810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_RIVER_0453CA810 }}
          action: "close"

  deploy_backend_job:
    # This job deploys the backend application to Azure App Service.
    # It only runs on pushes to the main branch.
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    # This job depends on the frontend build and deploy job.
    # Remove `needs` to run in parallel with the frontend deployment.
    needs: build_and_deploy_job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # The following steps assume a Node.js backend in the /backend folder.
      # Please adjust the path and build steps if your backend uses a different
      # technology or is in a different location.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies and build
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'portfolio-backend-api123'
          # Create a secret in your GitHub repository settings called AZURE_WEBAPP_PUBLISH_PROFILE
          # with the content of the publish profile from your Azure App Service.
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
